Repository atharva-narkhede/Hacktober2023, pull requests merged in 2023-10, with the labels that each got.

#1 Create fp-growth-algo
  Commit here/fp-growth-algo
Labels: good first issue, hacktober-accepted, hacktoberfest

#3 Create FP-Growth-Code
  FP-Growth-Code
Labels: documentation, enhancement, good first issue, hacktober-accepted, hacktoberfest

#2 C++ leetcode solution
  Commit here/C++/132Pattern.cpp
Labels: documentation, enhancement, good first issue, hacktober-accepted, hacktoberfest

#4 Create FP-Tree-Construction-Algorithm
  FP-Tree-Construction-Algorithm
Labels: documentation, good first issue, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#5 Create apriori-algo
  apriori-algo
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#6 Create code1
  bst/code1.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#7 Create even.c
  even.c
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#8 Create Generatingfrequentpatterngrowth
  Generatingfrequentpatterngrowth
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#9 Update readme.md
  Commit here/readme.md
Labels: documentation, good first issue, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#10 Create API Testing in C++
  API Testing in C++
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#11 Create Design HashMap.cpp
  Commit here/C++/Design HashMap.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#12 Add files via upload
  Commit here/C++/anagram_string.cpp
Labels: documentation, good first issue, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#14 Create N_queens.cpp
  Commit here/C++/N_queens.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#16 Create ZigZagTreeTraversal.cpp
  Commit here/ZigZagTreeTraversal.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#17 Create ShellSort.java
  ShellSort.java
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#20 Create Multiple_Inheritance.cpp
  Multiple_Inheritance.cpp
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#21 Create knn algo
  knn algo
Labels: hacktoberfest, hacktoberfest-accepted

#18 Humannx2 patch 3
  Floyd_Warshall.py
  Johnsons.py
  Multistage graph
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Create fibonacci.cpp
  fibonacci.cpp
Labels: hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#23 Create HeapSort.cpp
  HeapSort.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#25 Create Check for Balanced Tree.cpp
  Check for Balanced Tree.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#26 Update Design HashMap.cpp
  Commit here/C++/Design HashMap.cpp
Labels: documentation, hacktober-accepted, hacktoberfest, hacktoberfest-accepted

#28 Added the Binary Search Algorithm
  Commit here/C++/BinarySearch/BinarySearch.cpp
Labels: documentation, enhancement, hacktober-accepted, hacktoberfest, hacktoberfest-accepted
